spring.application.name: green-scheduling-spring-boot-demo

server:
  port: 8088


greenscheduled:
  enabled: true
  jobExecutors: 10
  overdueGracePeriod: PT5S
  shutdownGracePeriod: PT3S
  startMode: NORMAL
  apiKey: <insert>
  apiUrl: https://api.carbonintensity.io
